server:
  port: 8080

spring:
  application:
    name: movie-booking-backend
  web:
    cors:
      allowed-origins: "http://localhost:5173,http://localhost:5174,http://localhost:5175"
      allowed-methods: "GET,POST,PUT,DELETE,OPTIONS"
      allowed-headers: "*"
      allow-credentials: true